app_name = "FullTimeTeacher"
app_version = "0.1.0"
server_port = 9999

[mysql]
username = "root"
password = "rootroot"
host = "localhost"
port = 3306
db_name = "fulltimeteacher"


[jwt]
secret_key = "aaronlikeprogramming"

#token过期时间，单位小时
expiration_time = "24"

[redis]
host = "localhost"
port = 6380
password = ""
db = 0

[email]
host = "smtp.163.com"
port = 465
user = "15664621607@163.com"
password = "KTfcXrQuAcKjRAKz"
from = "15664621607@163.com"
alias = "Full Time Teacher"



