package models

import "gorm.io/gorm"

// AutoGenerated 结构体·
type UserInfo struct {
	UserID        string `json:"user_id,omitempty" gorm:"primaryKey;size:36"`   // 用户ID，设置为主键，长度为36
	Username      string `json:"username,omitempty" gorm:"size:100;unique"`     // 用户名，设置为唯一，长度为100
	Email         string `json:"email,omitempty" gorm:"size:100;unique"`        // 邮箱，设置为唯一，长度为100
	Password      string `json:"password,omitempty" gorm:"size:255"`            // 密码，长度为255
	Avatar        string `json:"avatar,omitempty" gorm:"size:255"`              // 头像，长度为255
	Sex           string `json:"sex,omitempty" gorm:"size:1;default:2"`         // 性别，长度为1， 0：女，1：男，2：未知
	Bio           string `json:"bio,omitempty" gorm:"size:500"`                 // 个人简介，长度为500
	LastLoginIp   string `json:"last_login_ip,omitempty" gorm:"size:50"`        // 最后一次登录的IP，长度为50
	LastLoginTime string `json:"last_login_time,omitempty" gorm:"size:20"`      // 最后一次登录的时间，长度为20
	CreateTime    string `json:"create_time,omitempty" gorm:"size:20"`          // 注册时间，长度为20
	Status        string `json:"status,omitempty" gorm:"size:1;default:1"`      // 状态，长度为20，默认值为1 1：正常，0：锁定
	Experience    string `json:"experience,omitempty" gorm:"size:10;default:0"` // 经验，长度为10，默认值为0
}

func (ui *UserInfo) TableName() string {
	return "user_info"
}

func NewUserTable(db *gorm.DB) error {
	//开启自动迁移
	return db.AutoMigrate(&UserInfo{})
}
